### ISSUE TITLE
Bug Fix Required

### ISSUE THREAD

**Issue by desvasicek** [desvasicek/Pigeon2D#4]
**Describe the bug**
When I run a file using the [Example Code](https://github.com/desvasicek/Pigeon2D/blob/main/README.md#tutorial), It gives me the error:

```python
Traceback (most recent call last):
  File "/home/therealpenguin/example.py", line 2, in <module>
    import Pigeon2d as p
ModuleNotFoundError: No module named 'Pigeon2d'
```

**To Reproduce**
1. Run [Example Code](https://github.com/desvasicek/Pigeon2D/blob/main/README.md#tutorial)
2. See error

**Expected behavior**
When you run [the code](https://github.com/desvasicek/Pigeon2D/blob/main/README.md#tutorial) it will produce the following error:

```python
Traceback (most recent call last):
  File "/home/therealpenguin/example.py", line 2, in <module>
    import Pigeon2d as p
ModuleNotFoundError: No module named 'Pigeon2d'
```

**Screenshots**
[Screen Recording](https://user-images.githubusercontent.com/84301435/178160525-dff8bf66-7d48-4c86-8b0d-ece01cdf841f.mp4)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi
 - IDE: [Python 3 IDE/IDLE](https://docs.python.org/3.9/library/idle.html)
 - 
**Assignment**
Anyone who is available

**Comment by desvasicek** [comment]
@desvasicek I know I am owner, but I don't know how to fix this.

**Comment by desvasicek** [comment]
Fixed by @moises0108, see https://github.com/desvasicek/Pigeon2D/commit/7e08b0258f6398a549af964ffffc49a01160d3d1
